version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: heimdall_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  server:
    image: linuxserver/heimdall:2.6.1@sha256:202f2b35e3343df9f87ece2f5f313e02e3451ccf47eb52f26746e1f7eb61920e
    volumes:
      - ${APP_DATA_DIR}/config:/config
    environment:
      - PUID=1000
      - PGID=1000
    restart: on-failure