version: "3.7"

services:
   app_proxy:
      environment:
         APP_HOST: minio_web_1
         APP_PORT: 9011
         PROXY_AUTH_ADD: "false"

   web:
      image: "quay.io/minio/minio:RELEASE.2024-07-26T20-48-21Z@sha256:9ef3d0514c0636e86e3db6b2a21c21d4035c17a47ea5464658f2f5d24afd15c6"
      restart: on-failure
      user: "1000:1000"
      stop_grace_period: 1m
      ports:
         # MinIO Api Server Port
         - "9010:9000"
      command: ["server", "/data"]
      volumes:
         - ${APP_DATA_DIR}/data/minio:/data
      environment:
         MINIO_ROOT_USER: "umbrel"
         MINIO_ROOT_PASSWORD: "$APP_PASSWORD"
         MINIO_CONSOLE_ADDRESS: ":9011"